// src/utils/visaDict.ts

export const VISA_DICT: any = {
    kr: {
        title: "E-7-4 비자 시뮬레이터",
        subtitle: "내 점수를 확인하고 미래를 준비하세요",
        myScore: "내 점수",
        passScore: "합격 기준",
        pass: "합격 가능!",
        fail: "부족합니다",
        eligibility: "기본 요건",
        income: "평균 소득 (2년)",
        korean: "한국어 능력",
        age: "나이",
        bonus: "가점 항목",
        penalty: "감점 항목",
        entryDate: "최초 입국일",
        birthYear: "출생년도",
        calculate: "계산하기",
        reset: "초기화",
        years: "년",
        months: "개월",
        stayDuration: "체류 기간",
        minRequirement: "최소 요건 미달",
        minReqDesc: "소득 2,600만원 & 한국어 2급 필수",
        bonusItems: {
            rec: "추천서 (중앙/지자체/기업)",
            work: "현 직장 3년 근속",
            remote: "인구감소지역 근무",
            degree: "국내 학위/자격증",
            driverLicense: "운전면허증",
        },
        penaltyItems: {
            fine: "벌금 납부",
            tax: "세금 체납",
            immigration: "출입국 위반",
        },
        // 추천서 항목 설명
        recDesc: {
            central: "중앙부처 (30점)",
            local: "광역지자체 (30점)",
            company: "고용기업체 (50점)",
        },
        recDescKr: {
            central: "중앙부처 추천서: 정부 부처에서 발급하는 추천서로, 30점이 부여됩니다.",
            local: "광역지자체 추천서: 지방자치단체에서 발급하는 추천서로, 30점이 부여됩니다.",
            company: "고용기업체 추천서: 현재 근무 중인 기업에서 발급하는 추천서로, 50점이 부여됩니다.",
        },
    },
    vn: {
        title: "Mô phỏng Visa E-7-4",
        subtitle: "Kiểm tra điểm số và chuẩn bị cho tương lai",
        myScore: "Điểm của tôi",
        passScore: "Điểm chuẩn",
        pass: "Đậu!",
        fail: "Chưa đủ điểm",
        eligibility: "Điều kiện cơ bản",
        income: "Thu nhập (2 năm)",
        korean: "Tiếng Hàn",
        age: "Tuổi",
        bonus: "Điểm cộng",
        penalty: "Điểm trừ",
        entryDate: "Ngày nhập cảnh",
        birthYear: "Năm sinh",
        calculate: "Tính toán",
        reset: "Làm lại",
        years: "Năm",
        months: "Tháng",
        stayDuration: "Thời gian ở Hàn",
        minRequirement: "Không đủ điều kiện",
        minReqDesc: "Cần thu nhập 26tr won & Topik 2",
        bonusItems: {
            rec: "Thư giới thiệu",
            work: "Làm 3 năm tại cty hiện tại",
            remote: "Làm việc ở vùng sâu",
            degree: "Bằng cấp tại Hàn",
            driverLicense: "Bằng lái xe",
        },
        penaltyItems: {
            fine: "Nộp phạt",
            tax: "Nợ thuế",
            immigration: "Vi phạm luật cư trú",
        },
        recDesc: {
            central: "Thư giới thiệu từ Bộ Trung ương (30 điểm)",
            local: "Thư giới thiệu từ Chính quyền địa phương (30 điểm)",
            company: "Thư giới thiệu từ Công ty tuyển dụng (50 điểm)",
        },
        recDescKr: {
            central: "Thư giới thiệu từ Bộ Trung ương: Được cấp bởi các bộ chính phủ, mang lại 30 điểm.",
            local: "Thư giới thiệu từ Chính quyền địa phương: Được cấp bởi chính quyền địa phương, mang lại 30 điểm.",
            company: "Thư giới thiệu từ Công ty tuyển dụng: Được cấp bởi công ty bạn đang làm việc, mang lại 50 điểm.",
        },
    },
    kh: {
        title: "ការគណនាពិន្ទុវីសា E-7-4",
        subtitle: "ពិនិត្យពិន្ទុរបស់អ្នកសម្រាប់អនាគត",
        myScore: "ពិន្ទុរបស់អ្នក",
        passScore: "ពិន្ទុជាប់",
        pass: "ជាប់!",
        fail: "មិនទាន់គ្រប់",
        eligibility: "លក្ខខណ្ឌមូលដ្ឋាន",
        income: "ប្រាក់ចំណូល (២ឆ្នាំ)",
        korean: "ភាសាកូរ៉េ",
        age: "អាយុ",
        bonus: "ពិន្ទុបន្ថែម",
        penalty: "ពិន្ទុដក",
        entryDate: "ថ្ងៃចូលកូរ៉េ",
        birthYear: "ឆ្នាំកំណើត",
        calculate: "គណនា",
        reset: "កំណត់ឡើងវិញ",
        years: "ឆ្នាំ",
        months: "ខែ",
        stayDuration: "រយៈពេលស្នាក់នៅ",
        minRequirement: "មិនគ្រប់លក្ខខណ្ឌ",
        minReqDesc: "ចំណូល ២៦លានវ៉ុន & Topik ២",
        bonusItems: {
            rec: "លិខិតណែនាំ",
            work: "ធ្វើការ ៣ឆ្នាំកន្លែងចាស់",
            remote: "តំបន់ជនបទ",
            degree: "សញ្ញាបត្រកូរ៉េ",
            driverLicense: "ប័ណ្ណបើកបរ",
        },
        penaltyItems: {
            fine: "បង់ពិន័យ",
            tax: "ជំពាក់ពន្ធ",
            immigration: "ល្មើសច្បាប់អន្តោប្រវេសន៍",
        },
        recDesc: {
            central: "លិខិតណែនាំពីក្រសួងកណ្តាល (៣០ពិន្ទុ)",
            local: "លិខិតណែនាំពីរដ្ឋាភិបាលតំបន់ (៣០ពិន្ទុ)",
            company: "លិខិតណែនាំពីក្រុមហ៊ុនជួល (៥០ពិន្ទុ)",
        },
        recDescKr: {
            central: "លិខិតណែនាំពីក្រសួងកណ្តាល៖ ផ្តល់ដោយក្រសួងរដ្ឋាភិបាល ផ្តល់ពិន្ទុ ៣០។",
            local: "លិខិតណែនាំពីរដ្ឋាភិបាលតំបន់៖ ផ្តល់ដោយរដ្ឋាភិបាលតំបន់ ផ្តល់ពិន្ទុ ៣០។",
            company: "លិខិតណែនាំពីក្រុមហ៊ុនជួល៖ ផ្តល់ដោយក្រុមហ៊ុនដែលអ្នកធ្វើការ ផ្តល់ពិន្ទុ ៥០។",
        },
    },
    mm: {
        title: "E-7-4 ဗီဇာ အမှတ်တွက်မယ်",
        subtitle: "သင့်အနာဂတ်အတွက် အမှတ်စစ်ဆေးပါ",
        myScore: "ရမှတ်",
        passScore: "အောင်မှတ်",
        pass: "အောင်မြင်သည်!",
        fail: "မလုံလောက်ပါ",
        eligibility: "အခြေခံလိုအပ်ချက်",
        income: "ဝင်ငွေ (၂နှစ်)",
        korean: "ကိုရီးယားစာ",
        age: "အသက်",
        bonus: "အပိုဆုမှတ်",
        penalty: "အနှုတ်မှတ်",
        entryDate: "ရောက်ရှိရက်စွဲ",
        birthYear: "မွေးသက္ကရာဇ်",
        calculate: "တွက်မည်",
        reset: "ပြန်စမည်",
        years: "နှစ်",
        months: "လ",
        stayDuration: "နေထိုင်သည့်ကာလ",
        minRequirement: "မပြည့်မီပါ",
        minReqDesc: "ဝင်ငွေ သိန်း၂၆၀ & Topik 2",
        bonusItems: {
            rec: "ထောက်ခံစာ",
            work: "လက်ရှိအလုပ် ၃နှစ်",
            remote: "နယ်ဘက်အလုပ်",
            degree: "ကိုရီးယားဘွဲ့",
            driverLicense: "ယာဉ်မောင်းလိုင်စင်",
        },
        penaltyItems: {
            fine: "ဒဏ်ကြေး",
            tax: "အခွန်ကြွေး",
            immigration: "လဝက ပြစ်မှု",
        },
        recDesc: {
            central: "အလယ်အစိုးရ ထောက်ခံစာ (၃၀မှတ်)",
            local: "ဒေသခံအစိုးရ ထောက်ခံစာ (၃၀မှတ်)",
            company: "အလုပ်ရှင် ကုမ္ပဏီ ထောက်ခံစာ (၅၀မှတ်)",
        },
        recDescKr: {
            central: "အလယ်အစိုးရ ထောက်ခံစာ - အစိုးရဌာနများမှ ထုတ်ပေးပြီး ၃၀မှတ် ရရှိပါသည်။",
            local: "ဒေသခံအစိုးရ ထောက်ခံစာ - ဒေသခံအစိုးရမှ ထုတ်ပေးပြီး ၃၀မှတ် ရရှိပါသည်။",
            company: "အလုပ်ရှင် ကုမ္ပဏီ ထောက်ခံစာ - လက်ရှိအလုပ်လုပ်နေသော ကုမ္ပဏီမှ ထုတ်ပေးပြီး ၅၀မှတ် ရရှိပါသည်။",
        },

    },
    uz: {
        title: "E-7-4 Viza Hisoblagich",
        subtitle: "Kelajagingiz uchun ballni tekshiring",
        myScore: "Ballim",
        passScore: "O'tish balli",
        pass: "O'tdingiz!",
        fail: "Yetarli emas",
        eligibility: "Asosiy talablar",
        income: "Daromad (2 yil)",
        korean: "Koreys tili",
        age: "Yosh",
        bonus: "Qo'shimcha ball",
        penalty: "Jarimalar",
        entryDate: "Kirish sanasi",
        birthYear: "Tug'ilgan yil",
        calculate: "Hisoblash",
        reset: "Qayta",
        years: "Yil",
        months: "Oy",
        stayDuration: "Koreyada yashash",
        minRequirement: "Talab bajarilmadi",
        minReqDesc: "Daromad 26mln & Topik 2",
        bonusItems: {
            rec: "Tavsiyanoma",
            work: "3 yil ishlash",
            remote: "Qishloq hududi",
            degree: "Koreya diplomi",
            driverLicense: "Haydovchilik guvohnomasi",
        },
        penaltyItems: {
            fine: "Jarima",
            tax: "Soliq qarzi",
            immigration: "Immigratsiya qoidabuzarligi",
        },
        recDesc: {
            central: "Markaziy hukumat tavsiyanomasi (30 ball)",
            local: "Mahalliy hukumat tavsiyanomasi (30 ball)",
            company: "Ish beruvchi kompaniya tavsiyanomasi (50 ball)",
        },
        recDescKr: {
            central: "Markaziy hukumat tavsiyanomasi - Hukumat idoralari tomonidan beriladi va 30 ball beradi.",
            local: "Mahalliy hukumat tavsiyanomasi - Mahalliy hukumat tomonidan beriladi va 30 ball beradi.",
            company: "Ish beruvchi kompaniya tavsiyanomasi - Siz ishlayotgan kompaniya tomonidan beriladi va 50 ball beradi.",
        },

    }
};